version: '3.4'
services:

  zookeeper:
    extends:
      file: docker-compose-base.yml
      service: zookeeper

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - /tmp/logs/nginx/:/var/log/nginx/
    depends_on:
      - fastapi
    ports:
      - 80:80

  broker:
    extends:
      file: docker-compose-base.yml
      service: broker
    depends_on:
      - zookeeper

  clickhouse-node1:
    extends:
      file: docker-compose-base.yml
      service: clickhouse-node1
    depends_on:
      - zookeeper

  clickhouse-node2:
    extends:
      file: docker-compose-base.yml
      service: clickhouse-node2
    depends_on:
      - zookeeper

  mongo:
    extends:
      file: docker-compose-base.yml
      service: mongo
    expose:
      - "${DB_PORT}"

  mongo-express:
    extends:
      file: docker-compose-base.yml
      service: mongo-express
    expose:
      - "${ME_PORT}"

  fastapi:
    extends:
      file: docker-compose-base.yml
      service: fastapi
    depends_on:
      - mongo
      - broker